Mg/test (#69)
* added space

* added comment

* fix: removed vgs

* Update common dependency to v1.6.0 (#58)

Co-authored-by: test-dell-csi-extension-app[bot] <188170956+test-dell-csi-extension-app[bot]@users.noreply.github.com>

* added validation for input

* removed space

* added validation for common

---------

Co-authored-by: test-dell-csi-extension-app[bot] <188170956+test-dell-csi-extension-app[bot]@users.noreply.github.com>

diff --git a/.github/workflows/patch-release.yaml b/.github/workflows/patch-release.yaml
--- a/.github/workflows/patch-release.yaml
+++ b/.github/workflows/patch-release.yaml
@@ -45,6 +45,13 @@ jobs:
             exit 1
           fi
 
+          if [ -n "${{ github.event.inputs.common }}" ]; then
+            if [ -z "${{ github.event.inputs.replication }}" ] || [ -z "${{ github.event.inputs.migration }}" ]; then
+              echo "Error: If 'common' input is provided, both 'replication' and 'migration' must also be provided."
+              exit 1
+            fi
+          fi
+
       - name: Import GPG key
         uses: crazy-max/ghaction-import-gpg@v6
         with:
