Mg/test (#67)
* added space

* added comment

* fix: removed vgs

* Update common dependency to v1.6.0 (#58)

Co-authored-by: test-dell-csi-extension-app[bot] <188170956+test-dell-csi-extension-app[bot]@users.noreply.github.com>

* added validation for input

* removed space

---------

Co-authored-by: test-dell-csi-extension-app[bot] <188170956+test-dell-csi-extension-app[bot]@users.noreply.github.com>

diff --git a/.github/workflows/patch-release.yaml b/.github/workflows/patch-release.yaml
--- a/.github/workflows/patch-release.yaml
+++ b/.github/workflows/patch-release.yaml
@@ -28,7 +28,7 @@ on:
         description: 'Version for podmon module'
         required: false
         type: string
-  
+
 jobs:
   release-modules:
     runs-on: ubuntu-latest
@@ -37,6 +37,13 @@ jobs:
         uses: actions/checkout@v2
         with:
           fetch-depth: 0  # Fetch all history for all tags
+
+      - name: Validate inputs
+        run: |
+          if [ -z "${{ github.event.inputs.replication }}" ] && [ -z "${{ github.event.inputs.migration }}" ] && [ -z "${{ github.event.inputs.common }}" ] && [ -z "${{ github.event.inputs.podmon }}" ]; then
+            echo "Error: At least one input must be provided."
+            exit 1
+          fi
 
       - name: Import GPG key
         uses: crazy-max/ghaction-import-gpg@v6
